window.PUBLICATIONS = [
  {
    "id": "10.1016/j.apr.2026.102990",
    "doi": "10.1016/j.apr.2026.102990",
    "language": "en",
    "role": "coauthor",
    "title": "Seasonal pollution characteristics, sources and environmental impact of volatile organic compounds in urban area in central China",
    "authors": [
      "Lihua Pan",
      "Dong Zhang",
      "Bowen Zhang",
      "Minghao Yuan",
      "Yifei Xu",
      "Jie Tao",
      "Ruiqin Zhang",
      "Xiao Li"
    ],
    "year": 2026,
    "month": 7,
    "journal": "Atmospheric Pollution Research",
    "volume": "17",
    "issue": "7",
    "pages": "102990",
    "url": "https://doi.org/10.1016/j.apr.2026.102990"
  },
  {
    "id": "10.1016/j.atmosenv.2025.121762",
    "doi": "10.1016/j.atmosenv.2025.121762",
    "language": "en",
    "role": "coauthor",
    "title": "Quantifying source-specific formaldehyde contributions to photochemical oxidant formation in a highly polluted Chinese megacity",
    "authors": [
      "Yunxiang Zhang",
      "Jie Tao",
      "Panru Kang",
      "Dong Zhang",
      "Yifei Xu",
      "Mingkai Wang",
      "Shenbo Wang",
      "Ruiqin Zhang"
    ],
    "year": 2026,
    "month": 2,
    "journal": "Atmospheric Environment",
    "volume": "367",
    "issue": "",
    "pages": "121762",
    "url": "https://doi.org/10.1016/j.atmosenv.2025.121762"
  },
  {
    "id": "10.1016/j.apr.2025.102717",
    "doi": "10.1016/j.apr.2025.102717",
    "language": "en",
    "role": "coauthor",
    "title": "PAN pollution during PM2.5 episodes in a traffic hub city in central China: mechanisms and implications",
    "authors": [
      "Xinshuai Song",
      "Xiao Li",
      "Dong Zhang",
      "Zhe Dong",
      "Xuan Lu",
      "Bowen Zhang",
      "Ruiqin Zhang"
    ],
    "year": 2026,
    "month": 1,
    "journal": "Atmospheric Pollution Research",
    "volume": "17",
    "issue": "1",
    "pages": "102717",
    "url": "https://doi.org/10.1016/j.apr.2025.102717"
  },
  {
    "id": "10.1016/j.atmosenv.2025.121412",
    "doi": "10.1016/j.atmosenv.2025.121412",
    "language": "en",
    "role": "first",
    "title": "Unraveling the formation and precursor sensitivity of peroxyacetyl nitrate (PAN) in urban photochemical pollution: A case study of Zhengzhou",
    "authors": [
      "Dong Zhang",
      "Xiao Li",
      "Qi Ying",
      "Qixiang Xu",
      "Xuan Lu",
      "Minghao Yuan",
      "Yifei Xu",
      "Zhangsen Dong"
    ],
    "year": 2025,
    "month": 11,
    "journal": "Atmospheric Environment",
    "volume": "360",
    "issue": "",
    "pages": "121412",
    "url": "https://doi.org/10.1016/j.atmosenv.2025.121412"
  },
  {
    "id": "10.1016/j.jes.2024.01.033",
    "doi": "10.1016/j.jes.2024.01.033",
    "language": "en",
    "role": "coauthor",
    "title": "Establishment and verification of anthropogenic speciated VOCs emission inventory of Central China",
    "authors": [
      "Xuan Lu",
      "Dong Zhang",
      "Lanxin Wang",
      "Shefang Wang",
      "Xinran Zhang",
      "Yali Liu",
      "Keying Chen",
      "Xinshuai Song",
      "Shasha Yin",
      "Ruiqin Zhang",
      "Shanshan Wang",
      "Minghao Yuan"
    ],
    "year": 2025,
    "month": 3,
    "journal": "Journal of Environmental Sciences",
    "volume": "149",
    "issue": "",
    "pages": "406-418",
    "url": "https://doi.org/10.1016/j.jes.2024.01.033"
  },
  {
    "id": "10.5194/acp-24-13587-2024",
    "doi": "10.5194/acp-24-13587-2024",
    "language": "en",
    "role": "cofirst",
    "title": "The variations in volatile organic compounds based on the policy change for Omicron in the traffic hub of Zhengzhou",
    "authors": [
      "Bowen Zhang",
      "Dong Zhang",
      "Zhe Dong",
      "Xinshuai Song",
      "Ruiqin Zhang",
      "Xiao Li"
    ],
    "year": 2024,
    "month": 12,
    "journal": "Atmospheric Chemistry and Physics",
    "volume": "24",
    "issue": "23",
    "pages": "13587-13601",
    "url": "https://doi.org/10.5194/acp-24-13587-2024",
    "fulltext": "https://acp.copernicus.org/articles/24/13587/2024/"
  },
  {
    "id": "10.5194/acp-24-9885-2024",
    "doi": "10.5194/acp-24-9885-2024",
    "language": "en",
    "role": "coauthor",
    "title": "Measurement report: Elevated atmospheric ammonia may promote particle pH and HONO formation – insights from the COVID-19 pandemic",
    "authors": [
      "Xinyuan Zhang",
      "Lingling Wang",
      "Nan Wang",
      "Shuangliang Ma",
      "Shenbo Wang",
      "Ruiqin Zhang",
      "Dong Zhang",
      "Mingkai Wang",
      "Hongyu Zhang"
    ],
    "year": 2024,
    "month": 9,
    "journal": "Atmospheric Chemistry and Physics",
    "volume": "24",
    "issue": "17",
    "pages": "9885-9898",
    "url": "https://doi.org/10.5194/acp-24-9885-2024",
    "fulltext": "https://acp.copernicus.org/articles/24/9885/2024/"
  },
  {
    "id": "10.1016/j.jclepro.2024.143401",
    "doi": "10.1016/j.jclepro.2024.143401",
    "language": "en",
    "role": "coauthor",
    "title": "Study on main sources of aerosol pH and new methods for additional reduction of PM2.5 during winter severe pollution: Based on the PMF-GAS model",
    "authors": [
      "Yunfei Wei",
      "Shuodi Wang",
      "Nan Jiang",
      "Dong Zhang",
      "Ruiqin Zhang"
    ],
    "year": 2024,
    "month": 9,
    "journal": "Journal of Cleaner Production",
    "volume": "471",
    "issue": "",
    "pages": "143401",
    "url": "https://doi.org/10.1016/j.jclepro.2024.143401"
  },
  {
    "id": "10.1016/j.jhazmat.2024.135122",
    "doi": "10.1016/j.jhazmat.2024.135122",
    "language": "en",
    "role": "coauthor",
    "title": "p‑Phenylenediamine antioxidants in PM2.5: New markers for traffic in positive matrix factorization source apportionment",
    "authors": [
      "Nan Jiang",
      "Xuexin Hao",
      "Zichen Wang",
      "Minzhen Li",
      "Dong Zhang",
      "Rong Cao",
      "Ruiqin Zhang",
      "Haijun Zhang",
      "Jiping Chen",
      "Ningbo Geng"
    ],
    "year": 2024,
    "month": 9,
    "journal": "Journal of Hazardous Materials",
    "volume": "476",
    "issue": "",
    "pages": "135122",
    "url": "https://doi.org/10.1016/j.jhazmat.2024.135122"
  },
  {
    "id": "10.13227/j.hjkx.202310049",
    "doi": "10.13227/j.hjkx.202310049",
    "language": "zh",
    "role": "coauthor",
    "title": "基于光化学损失的郑州市夏季VOCs污染特征、来源及环境影响",
    "titleEn": "Characteristics, Sources Analysis, and Environmental Impacts of VOCs Based on Photochemical Loss in Summer in Zhengzhou",
    "authors": [
      "李卓",
      "王冰",
      "王甜甜",
      "张栋",
      "宋鑫帅",
      "袁明浩",
      "卢轩",
      "王文举",
      "尹沙沙",
      "张瑞芹"
    ],
    "authorsEn": [
      "Zhuo Li",
      "Bing Wang",
      "Tian-Tian Wang",
      "Dong Zhang",
      "Xin-Shuai Song",
      "Ming-Hao Yuan",
      "Xuan Lu",
      "Wen-Ju Wang",
      "Sha-Sha Yin",
      "Rui-Qin Zhang"
    ],
    "year": 2024,
    "month": 9,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "45",
    "issue": "9",
    "pages": "5157–5167",
    "url": "https://doi.org/10.13227/j.hjkx.202310049",
    "source": "https://pubmed.ncbi.nlm.nih.gov/39323134/"
  },
  {
    "id": "10.5194/acp-24-8549-2024",
    "doi": "10.5194/acp-24-8549-2024",
    "language": "en",
    "role": "first",
    "title": "Characteristics and sources of nonmethane volatile organic compounds (NMVOCs) and O3–NOx–NMVOC relationships in Zhengzhou, China",
    "authors": [
      "Dong Zhang",
      "Xiao Li",
      "Minghao Yuan",
      "Yifei Xu",
      "Qixiang Xu",
      "Fangcheng Su",
      "Shenbo Wang",
      "Ruiqin Zhang"
    ],
    "year": 2024,
    "month": 8,
    "journal": "Atmospheric Chemistry and Physics",
    "volume": "24",
    "issue": "15",
    "pages": "8549-8567",
    "url": "https://doi.org/10.5194/acp-24-8549-2024",
    "fulltext": "https://acp.copernicus.org/articles/24/8549/2024/"
  },
  {
    "id": "10.13227/j.hjkx.202301125",
    "doi": "10.13227/j.hjkx.202301125",
    "language": "zh",
    "role": "coauthor",
    "title": "郑州市冬夏季污染过程中大气VOCs污染特征、来源解析及活性分析",
    "titleEn": "Pollution Characteristics, Source Analysis, and Activity Analysis of Atmospheric VOCs During Winter and Summer Pollution in Zhengzhou",
    "authors": [
      "赖梦洁",
      "张栋",
      "于世杰",
      "宋鑫帅",
      "李晓",
      "张瑞芹"
    ],
    "authorsEn": [
      "Meng-Jie Lai",
      "Dong Zhang",
      "Shi-Jie Yu",
      "Xin-Shuai Song",
      "Xiao Li",
      "Rui-Qin Zhang"
    ],
    "year": 2024,
    "month": 2,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "45",
    "issue": "2",
    "pages": "689–699",
    "url": "https://doi.org/10.13227/j.hjkx.202301125",
    "source": "https://www.hjkx.ac.cn/hjkx/ch/html/20240208.htm"
  },
  {
    "id": "10.1016/j.atmosres.2023.106958",
    "doi": "10.1016/j.atmosres.2023.106958",
    "language": "en",
    "role": "coauthor",
    "title": "Simultaneous observations of peroxyacetyl nitrate and ozone in Central China during static management of COVID-19: Regional transport and thermal decomposition",
    "authors": [
      "Xinshuai Song",
      "Dong Zhang",
      "Xiao Li",
      "Xuan Lu",
      "Mingkai Wang",
      "Bowen Zhang",
      "Ruiqin Zhang"
    ],
    "year": 2023,
    "month": 10,
    "journal": "Atmospheric Research",
    "volume": "294",
    "issue": "",
    "pages": "106958",
    "url": "https://doi.org/10.1016/j.atmosres.2023.106958"
  },
  {
    "id": "10.1016/j.envpol.2023.121465",
    "doi": "10.1016/j.envpol.2023.121465",
    "language": "en",
    "role": "coauthor",
    "title": "Strong relations of peroxyacetyl nitrate (PAN) formation to alkene and nitrous acid during various episodes",
    "authors": [
      "Xueqi Qiao",
      "Mei Sun",
      "Yifei Wang",
      "Dong Zhang",
      "Ruiqin Zhang",
      "Bu Zhao",
      "Jianbo Zhang"
    ],
    "year": 2023,
    "month": 6,
    "journal": "Environmental Pollution",
    "volume": "326",
    "issue": "",
    "pages": "121465",
    "url": "https://doi.org/10.1016/j.envpol.2023.121465"
  },
  {
    "id": "10.13227/j.hjkx.202203117",
    "doi": "10.13227/j.hjkx.202203117",
    "language": "zh",
    "role": "coauthor",
    "title": "郑州市多站点大气VOCs变化特征及源解析",
    "titleEn": "Variation Characteristics and Source Apportionment of Atmospheric VOCs at Multi-sites in Zhengzhou",
    "authors": [
      "王冰",
      "尹沙沙",
      "黄爱枝",
      "张栋",
      "卢轩",
      "张瑞芹"
    ],
    "authorsEn": [
      "Bing Wang",
      "Sha-Sha Yin",
      "Ai-Zhi Huang",
      "Dong Zhang",
      "Xuan Lu",
      "Rui-Qin Zhang"
    ],
    "year": 2023,
    "month": 2,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "44",
    "issue": "2",
    "pages": "699–708",
    "url": "https://doi.org/10.13227/j.hjkx.202203117",
    "source": "https://pubmed.ncbi.nlm.nih.gov/36775594/"
  },
  {
    "id": "10.5194/acp-22-14859-2022",
    "doi": "10.5194/acp-22-14859-2022",
    "language": "en",
    "role": "coauthor",
    "title": "Measurement report: Intra- and interannual variability and source apportionment of volatile organic compounds during 2018–2020 in Zhengzhou, central China",
    "authors": [
      "Shijie Yu",
      "Shenbo Wang",
      "Ruixin Xu",
      "Dong Zhang",
      "Meng Zhang",
      "Fangcheng Su",
      "Xuan Lu",
      "Xiao Li",
      "Ruiqin Zhang",
      "Lingling Wang"
    ],
    "year": 2022,
    "month": 11,
    "journal": "Atmospheric Chemistry and Physics",
    "volume": "22",
    "issue": "22",
    "pages": "14859-14878",
    "url": "https://doi.org/10.5194/acp-22-14859-2022",
    "fulltext": "https://acp.copernicus.org/articles/22/14859/2022/"
  },
  {
    "id": "10.13227/j.hjkx.202109153",
    "doi": "10.13227/j.hjkx.202109153",
    "language": "zh",
    "role": "corresponding",
    "title": "济源冬季VOCs污染特征、来源和SOAP",
    "titleEn": "Characteristics, Sources, and SOAP of VOCs During Winter in Jiyuan",
    "authors": [
      "王芳",
      "李利霞",
      "王红果",
      "赵宗生",
      "张建平",
      "张栋"
    ],
    "authorsEn": [
      "Fang Wang",
      "Li-Xia Li",
      "Hong-Guo Wang",
      "Zong-Sheng Zhao",
      "Jian-Ping Zhang",
      "Dong Zhang"
    ],
    "year": 2022,
    "month": 7,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "43",
    "issue": "7",
    "pages": "3451–3462",
    "url": "https://doi.org/10.13227/j.hjkx.202109153",
    "source": "https://www.hjkx.ac.cn/ch/reader/view_abstract.aspx?file_no=20220708&flag=1"
  },
  {
    "id": "10.1016/j.apr.2022.101390",
    "doi": "10.1016/j.apr.2022.101390",
    "language": "en",
    "role": "coauthor",
    "title": "Characteristics, source analysis and chemical reactivity of ambient VOCs in a heavily polluted city of central China",
    "authors": [
      "Aizhi Huang",
      "Shasha Yin",
      "Minghao Yuan",
      "Yifei Xu",
      "Shijie Yu",
      "Dong Zhang",
      "Xuan Lu",
      "Ruiqin Zhang"
    ],
    "year": 2022,
    "month": 4,
    "journal": "Atmospheric Pollution Research",
    "volume": "13",
    "issue": "4",
    "pages": "101390",
    "url": "https://doi.org/10.1016/j.apr.2022.101390"
  },
  {
    "id": "10.13227/j.hjkx.202107001",
    "doi": "10.13227/j.hjkx.202107001",
    "language": "zh",
    "role": "coauthor",
    "title": "郑州市典型污染过程PM1中重金属浓度、来源及健康风险评估",
    "titleEn": "Concentration, Source, and Health Risk Assessment of PM1 Heavy Metals in Typical Pollution Processes in Zhengzhou",
    "authors": [
      "翟诗婷",
      "王申博",
      "张栋",
      "赵孝囡",
      "杨洁茹",
      "刘洋",
      "陈红阳",
      "张瑞芹"
    ],
    "authorsEn": [
      "Shi-Ting Zhai",
      "Shen-Bo Wang",
      "Dong Zhang",
      "Xiao-Nan Zhao",
      "Jie-Ru Yang",
      "Yang Liu",
      "Hong-Yang Chen",
      "Rui-Qin Zhang"
    ],
    "year": 2022,
    "month": 3,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "43",
    "issue": "3",
    "pages": "1180–1189",
    "url": "https://doi.org/10.13227/j.hjkx.202107001",
    "source": "https://www.hjkx.ac.cn/hjkx/ch/html/20220306.htm"
  },
  {
    "id": "10.1016/j.jes.2021.01.035",
    "doi": "10.1016/j.jes.2021.01.035",
    "language": "en",
    "role": "first",
    "title": "Characteristics, sources and health risks assessment of VOCs in Zhengzhou, China during haze pollution season",
    "authors": [
      "Dong Zhang",
      "Bing He",
      "Minghao Yuan",
      "Shijie Yu",
      "Shasha Yin",
      "Ruiqin Zhang"
    ],
    "year": 2021,
    "month": 10,
    "journal": "Journal of Environmental Sciences",
    "volume": "108",
    "issue": "",
    "pages": "44-57",
    "url": "https://doi.org/10.1016/j.jes.2021.01.035"
  },
  {
    "id": "10.1016/j.scitotenv.2021.147303",
    "doi": "10.1016/j.scitotenv.2021.147303",
    "language": "en",
    "role": "coauthor",
    "title": "Seasonal discrepancies in peroxyacetyl nitrate (PAN) and its correlation with ozone and PM2.5: Effects of regional transport from circumjacent industrial cities",
    "authors": [
      "Mei Sun",
      "Ying Zhou",
      "Yifei Wang",
      "Xiaochen Zheng",
      "Jia'nan Cui",
      "Dong Zhang",
      "Jianbo Zhang",
      "Ruiqin Zhang"
    ],
    "year": 2021,
    "month": 9,
    "journal": "Science of The Total Environment",
    "volume": "785",
    "issue": "",
    "pages": "147303",
    "url": "https://doi.org/10.1016/j.scitotenv.2021.147303"
  },
  {
    "id": "10.13227/j.hjkx.202002151",
    "doi": "10.13227/j.hjkx.202002151",
    "language": "zh",
    "role": "coauthor",
    "title": "郑州市少数民族运动会期间O3及VOCs污染特征的演变和评估",
    "titleEn": "Evolution and Evaluation of O3 and VOCs in Zhengzhou During the National Traditional Games of Ethnic Minorities Period",
    "authors": [
      "赵金帅",
      "于世杰",
      "王楠",
      "马双良",
      "王维思",
      "尹沙沙",
      "李一丹",
      "张栋",
      "张瑞芹"
    ],
    "authorsEn": [
      "Jin-Shuai Zhao",
      "Shi-Jie Yu",
      "Nan Wang",
      "Shuang-Liang Ma",
      "Wei-Si Wang",
      "Sha-Sha Yin",
      "Yi-Dan Li",
      "Dong Zhang",
      "Rui-Qin Zhang"
    ],
    "year": 2020,
    "month": 10,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "41",
    "issue": "10",
    "pages": "4436–4445",
    "url": "https://doi.org/10.13227/j.hjkx.202002151",
    "source": "https://pubmed.ncbi.nlm.nih.gov/33124375/"
  },
  {
    "id": "10.13227/j.hjkx.202001133",
    "doi": "10.13227/j.hjkx.202001133",
    "language": "zh",
    "role": "coauthor",
    "title": "郑州市某城区冬季不同污染水平大气VOCs特征及源解析",
    "titleEn": "Characteristics and Source Apportionment of VOCs at Different Pollution Levels During the Winter in an Urban Area in Zhengzhou",
    "authors": [
      "李一丹",
      "尹沙沙",
      "张瑞芹",
      "于世杰",
      "杨健",
      "张栋"
    ],
    "authorsEn": [
      "Yi-Dan Li",
      "Sha-Sha Yin",
      "Rui-Qin Zhang",
      "Shi-Jie Yu",
      "Jian Yang",
      "Dong Zhang"
    ],
    "year": 2020,
    "month": 8,
    "journal": "环境科学",
    "journalEn": "Environmental Science",
    "volume": "41",
    "issue": "8",
    "pages": "3500–3510",
    "url": "https://doi.org/10.13227/j.hjkx.202001133",
    "source": "https://pubmed.ncbi.nlm.nih.gov/33124322/"
  },
  {
    "id": "actasc-2020-2935",
    "doi": "",
    "language": "zh",
    "role": "first",
    "title": "郑州市冬季VOCs污染特征、来源及健康风险评估",
    "titleEn": "Characteristics, sources and health risk assessment of ambient VOCs in winter of Zhengzhou",
    "authors": [
      "张栋",
      "于世杰",
      "王楠",
      "马双良",
      "王维思",
      "尹沙沙",
      "李一丹",
      "郭旺",
      "张瑞芹"
    ],
    "authorsEn": [
      "Dong Zhang",
      "Shijie Yu",
      "Nan Wang",
      "Shuangliang Ma",
      "Weisi Wang",
      "Shasha Yin",
      "Yidan Li",
      "Wang Guo",
      "Ruiqin Zhang"
    ],
    "year": 2020,
    "month": 8,
    "journal": "环境科学学报",
    "journalEn": "Acta Scientiae Circumstantiae",
    "volume": "40",
    "issue": "8",
    "pages": "2935–2943",
    "url": "https://html.rhhz.net/hjkxxb/html/20200216001.htm",
    "source": "https://html.rhhz.net/hjkxxb/html/20200216001.htm"
  },
  {
    "id": "10.1016/j.chemosphere.2020.126283",
    "doi": "10.1016/j.chemosphere.2020.126283",
    "language": "en",
    "role": "coauthor",
    "title": "Characteristics, source apportionment and health risks of ambient VOCs during high ozone period at an urban site in central plain, China",
    "authors": [
      "Yidan Li",
      "Shasha Yin",
      "Shijie Yu",
      "Minghao Yuan",
      "Zhe Dong",
      "Dong Zhang",
      "Liuming Yang",
      "Ruiqin Zhang"
    ],
    "year": 2020,
    "month": 7,
    "journal": "Chemosphere",
    "volume": "250",
    "issue": "",
    "pages": "126283",
    "url": "https://doi.org/10.1016/j.chemosphere.2020.126283"
  }
];
